/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VindConsultingOnboardingRouteImport } from './routes/vind-consulting-onboarding'
import { Route as VikingdanmarkRouteImport } from './routes/vikingdanmark'
import { Route as TilgangRouteImport } from './routes/tilgang'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'

const VindConsultingOnboardingRoute =
  VindConsultingOnboardingRouteImport.update({
    id: '/vind-consulting-onboarding',
    path: '/vind-consulting-onboarding',
    getParentRoute: () => rootRouteImport,
  } as any)
const VikingdanmarkRoute = VikingdanmarkRouteImport.update({
  id: '/vikingdanmark',
  path: '/vikingdanmark',
  getParentRoute: () => rootRouteImport,
} as any)
const TilgangRoute = TilgangRouteImport.update({
  id: '/tilgang',
  path: '/tilgang',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/tilgang': typeof TilgangRoute
  '/vikingdanmark': typeof VikingdanmarkRoute
  '/vind-consulting-onboarding': typeof VindConsultingOnboardingRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/tilgang': typeof TilgangRoute
  '/vikingdanmark': typeof VikingdanmarkRoute
  '/vind-consulting-onboarding': typeof VindConsultingOnboardingRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/tilgang': typeof TilgangRoute
  '/vikingdanmark': typeof VikingdanmarkRoute
  '/vind-consulting-onboarding': typeof VindConsultingOnboardingRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cv'
    | '/tilgang'
    | '/vikingdanmark'
    | '/vind-consulting-onboarding'
    | '/cases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cv'
    | '/tilgang'
    | '/vikingdanmark'
    | '/vind-consulting-onboarding'
    | '/cases/$slug'
  id:
    | '__root__'
    | '/'
    | '/cv'
    | '/tilgang'
    | '/vikingdanmark'
    | '/vind-consulting-onboarding'
    | '/cases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  TilgangRoute: typeof TilgangRoute
  VikingdanmarkRoute: typeof VikingdanmarkRoute
  VindConsultingOnboardingRoute: typeof VindConsultingOnboardingRoute
  CasesSlugRoute: typeof CasesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vind-consulting-onboarding': {
      id: '/vind-consulting-onboarding'
      path: '/vind-consulting-onboarding'
      fullPath: '/vind-consulting-onboarding'
      preLoaderRoute: typeof VindConsultingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vikingdanmark': {
      id: '/vikingdanmark'
      path: '/vikingdanmark'
      fullPath: '/vikingdanmark'
      preLoaderRoute: typeof VikingdanmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tilgang': {
      id: '/tilgang'
      path: '/tilgang'
      fullPath: '/tilgang'
      preLoaderRoute: typeof TilgangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  TilgangRoute: TilgangRoute,
  VikingdanmarkRoute: VikingdanmarkRoute,
  VindConsultingOnboardingRoute: VindConsultingOnboardingRoute,
  CasesSlugRoute: CasesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
