/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VikingdanmarkRouteImport } from './routes/vikingdanmark'
import { Route as CvRouteImport } from './routes/cv'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'

const VikingdanmarkRoute = VikingdanmarkRouteImport.update({
  id: '/vikingdanmark',
  path: '/vikingdanmark',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/vikingdanmark': typeof VikingdanmarkRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/vikingdanmark': typeof VikingdanmarkRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cv': typeof CvRoute
  '/vikingdanmark': typeof VikingdanmarkRoute
  '/cases/$slug': typeof CasesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cv' | '/vikingdanmark' | '/cases/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cv' | '/vikingdanmark' | '/cases/$slug'
  id: '__root__' | '/' | '/cv' | '/vikingdanmark' | '/cases/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvRoute: typeof CvRoute
  VikingdanmarkRoute: typeof VikingdanmarkRoute
  CasesSlugRoute: typeof CasesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vikingdanmark': {
      id: '/vikingdanmark'
      path: '/vikingdanmark'
      fullPath: '/vikingdanmark'
      preLoaderRoute: typeof VikingdanmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvRoute: CvRoute,
  VikingdanmarkRoute: VikingdanmarkRoute,
  CasesSlugRoute: CasesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
